ndarray is a short form for N-dimensional array which is a important component of NumPy. It’s allows us to store and manipulate large amounts of data efficiently. All elements in an ndarray must be of same type making it a homogeneous array. This structure supports multiple dimensions which makes it ideal for handling complex datasets like those used in scientific computing or data analysis. With this we can perform fast and memory efficient operations on data.

In [1]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Attributes of ndarray
Understanding the attributes of an ndarray is important while working with NumPy effectively. Here are the key attributes:

1. ndarray.shape: Returns a tuple representing the shape (dimensions) of the array.
2. ndarray.ndim: Returns the number of dimensions (axes) of the array.
3. ndarray.size: Returns the total number of elements in the array.
4. ndarray.dtype: Provides the data type of the array elements.
5. ndarray.itemsize: Returns the size in bytes of each element

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  
print("Dimensions:", arr.ndim)  
print("Size:", arr.size) 
print("Data type:", arr.dtype)  
print("Item size:", arr.itemsize)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64
Item size: 8


### Array Indexing and Slicing
NumPy allows indexing and slicing operations on ndarrays which offers more flexibility compared to standard Python lists. Here's a overview:

1. Basic Indexing
We can access individual elements in an array using square brackets just like Python lists. The indexing starts at 0.

In [6]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


2. Slicing
It allows us to extract sub-arrays using a range of indices. The syntax is [start:stop] where start is inclusive and stop is exclusive.

In [7]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


3. Multi-dimensional Indexing
We can index and slice each dimension separately in multi-dimensional arrays. This allows us to access specific rows, columns or deeper dimensions of the array.


In [8]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr_2d[1, 2])  

print(arr_2d[0:2, 1:3])

6
[[2 3]
 [5 6]]


### Array Operations
NumPy allows us to perform operations on entire arrays which enables efficient computation without the need for explicit loops. These operations include:

1. Element-wise Operations
These are straightforward and allow us to perform arithmetic operations on each element of the array directly.

In [9]:
arr = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr + arr2)  
print(arr * arr2)  
print(arr - arr2)  
print(arr / arr2)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


2. Matrix Operations (Dot product)
It allow us to multiply two arrays or matrices and get a single value or another matrix.

In [10]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print(np.dot(matrix1, matrix2))

[[19 22]
 [43 50]]


3. Broadcasting
This feature enables us to perform operations on arrays of different shapes. NumPy automatically adjusts the smaller array to match the shape of the larger one for the operation.

In [11]:
arr = np.array([[1, 2], [3, 4]])

print(arr + 10)

[[11 12]
 [13 14]]


4. Reshaping and Flattening
NumPy provides functions to reshape or flatten arrays which is useful when working with machine learning or deep learning algorithms.

* Reshaping: Change the shape of an array while keeping the data same.
* Flattening: Convert multi-dimensional arrays into one-dimensional arrays

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  
print(reshaped_arr)
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print(flattened_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


Array indexing in NumPy refers to the method of accessing specific elements or subsets of data within an array. This feature allows us to retrieve, modify and manipulate data at specific positions or ranges helps in making it easier to work with large datasets. In this article, we’ll see the different ways to index and slice NumPy arrays which helps us to work with our data more effectively.

### 1. Accessing Elements in 1D Arrays
A 1D NumPy array is a sequence of values with positions called indices which starts at 0. We access elements by using these indices in square brackets like arr[0] for the first element. Negative indices count from the end so arr[-1] gives the last element.

In [14]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])

10


### 2. Accessing Elements in Multidimensional Arrays
In this we will see how to access elements in both 2D and 3D arrays using specific indices.

* 2D Arrays: We can access elements by specifying both row and column indices like matrix[row, column].

In [15]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1, 2])

6


##### 3D Arrays: It can be visualized as a stack of 2D arrays, we need three indices-

Depth: Specifies the 2D slice.  
Row: Specifies the row within the slice.  
Column: Specifies the column within the row.  
We can access elements by specifying row, column and depth indices like matrix[depth, row, column].

In [16]:
cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(cube[1, 2, 0])

16


### 3. Slicing Arrays
It allows us to extract a range of elements using the format start:stop:step. This can be done for both 1D and multidimensional arrays which allows us to select ranges of elements or submatrices easily.

Slicing 1D Arrays: For a 1D array, slicing returns a subset of elements between the start and stop indices.

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5])

print(arr[1:4])

[1 2 3]


Slicing Multidimensional Arrays: In this slicing can be applied to each dimension separately which allows us to extract submatrices or smaller blocks of data.

In [18]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]


### 4. Boolean Indexing
It allows us to filter elements from an array based on a condition and returns only those that meet it. We create a boolean array from a condition and use it to select elements and can combine conditions with logical operators.






In [20]:
arr=np.arange(1,20)
even_arr=arr[arr%2==0]
even_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

The condition arr > 20 returns True for elements greater than 20 so only 25 and 30 are selected and printed.  

We can also use logical operators like & (AND), | (OR) and ~ (NOT) to combine conditions.

In [22]:
even_arr=arr[(arr%2==0) & (arr<10)]
even_arr

array([2, 4, 6, 8])

### 5. Fancy Indexing
It is also known as Advanced Indexing which allows us access elements of an array by using another array or list of indices. This allows selecting multiple elements at once even if they are not next to each other which makes it easy to pick specific values from different positions in the array.

In [26]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])

[10 30 50]


### 6. Integer Array Indexing
It is similar to fancy indexing and uses an array of integers to select multiple elements from another array. This method allows us to access elements at specific, non-adjacent positions which makes it useful for extracting scattered data points.

In [24]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[[0, 2, 4]])

[1 3 5]


### 7. Modifying Array Elements
We can modify array elements directly by using indexing or slicing. This makes it easy to update specific elements or ranges of elements in an array.

In [27]:
arr = np.array([1, 2, 3, 4])

arr[1:3] = 99

print(arr)

[ 1 99 99  4]
