ndarray is a short form for N-dimensional array which is a important component of NumPy. It’s allows us to store and manipulate large amounts of data efficiently. All elements in an ndarray must be of same type making it a homogeneous array. This structure supports multiple dimensions which makes it ideal for handling complex datasets like those used in scientific computing or data analysis. With this we can perform fast and memory efficient operations on data.

In [1]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Attributes of ndarray
Understanding the attributes of an ndarray is important while working with NumPy effectively. Here are the key attributes:

1. ndarray.shape: Returns a tuple representing the shape (dimensions) of the array.
2. ndarray.ndim: Returns the number of dimensions (axes) of the array.
3. ndarray.size: Returns the total number of elements in the array.
4. ndarray.dtype: Provides the data type of the array elements.
5. ndarray.itemsize: Returns the size in bytes of each element

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  
print("Dimensions:", arr.ndim)  
print("Size:", arr.size) 
print("Data type:", arr.dtype)  
print("Item size:", arr.itemsize)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64
Item size: 8
