Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them. It automatically adjusts the smaller array to match the larger array's shape by replicating its values along the necessary dimensions. This makes element-wise operations more efficient by reducing memory usage and eliminating the need for loops. In this article, we will see how broadcasting works.

In [1]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])  
scalar = 10  

result = array_2d + scalar
print(result)

[[11 12 13]
 [14 15 16]]


### Working of Broadcasting in NumPy
Broadcasting applies specific rules to find whether two arrays can be aligned for operations or not that are:

2. Check Dimensions: Ensure the arrays have the same number of dimensions or expandable dimensions.
1. Dimension Padding: If arrays have different numbers of dimensions the smaller array is left-padded with ones.
3. Shape Compatibility: Two dimensions are compatible if they are equal or one of them is 1.
If these conditions aren’t met NumPy will raise a ValueError.

Lets see various examples for broadcasting below:  

Example 1: Broadcasting a Scalar to a 1D Array

In [2]:
arr = np.array([1, 2, 3])

res = arr + 1  
print(res)

[2 3 4]


Example 2: Broadcasting a 1D Array to a 2D Array
This example shows how a 1D array a1 is added to a 2D array a2. NumPy automatically expands the 1D array along the rows of the 2D array to perform element-wise addition.

In [3]:
a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
res = a1 + a2
print(res)

[[ 3  7 11]
 [ 9 13 17]]


Example 3: Broadcasting in Conditional Operations
We may need to apply a condition to an entire array or a subset of it. Broadcasting can help to perform these operations efficiently without needing loops.

In [4]:
ages = np.array([12, 24, 35, 45, 60, 72])

age_group = np.array(["Adult", "Minor"])

result = np.where(ages > 18, age_group[0], age_group[1])

print(result)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


Example 4: Using Broadcasting for Matrix Multiplication
In this example, each element of a 2D matrix is multiplied by the corresponding element in a broadcasted vector.

In [5]:
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
result = matrix * vector
print(result)

[[10 40]
 [30 80]]


Example 5: Scaling Data with Broadcasting
Consider a real-world scenario where we need to calculate the total calories in foods based on the amount of fats, proteins and carbohydrates. Each nutrient has a specific caloric value per gram.

Fats: 9 calories per gram (CPG)
Proteins: 4 CPG
Carbohydrates: 4 CPG  
Left table shows the original data with food items and their respective grams of fats, proteins and carbs. The array [3, 3, 8] represents the caloric values per gram for fats, proteins and carbs respectively. This array is being broadcast to match the dimensions of the original data and arrow indicates the broadcasting operation.

Broadcasting array is multiplied element-wise with each row of the original data.
As a result right table shows the result of the multiplication where each cell represents the caloric contribution of that specific nutrient in the food item.

In [6]:
food_data = np.array([[0.8, 2.9, 3.9], 
                      [52.4, 23.6, 36.5],
                      [55.2, 31.7, 23.9],
                      [14.4, 11, 4.9]])

caloric_values = np.array([3, 3, 8]) 

caloric_matrix = caloric_values 

calorie_breakdown = food_data * caloric_matrix
print(calorie_breakdown)

[[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]


Example 6: Adjusting Temperature Data Across Multiple Locations
Suppose you have a 2D array representing daily temperature readings across multiple cities and you want to apply a correction factor to each city’s temperature data.

In [7]:
temperatures = np.array([
    [30, 32, 34, 33, 31],  
    [25, 27, 29, 28, 26], 
    [20, 22, 24, 23, 21]  
])

corrections = np.array([1.5, -0.5, 2.0])

adjusted_temperatures = temperatures + corrections[:, np.newaxis]
print(adjusted_temperatures)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


Example 7: Normalizing Image Data
Normalization is important in many real-world scenarios like image processing and machine learning because it:

Centers data by subtracting the mean by ensuring features have zero mean.
Scales data by dividing by the standard deviation by ensuring features have unit variance.
Improves numerical stability and performance of algorithms like gradient descent.
Let's see how broadcasting simplifies normalization:

In [8]:
image = np.array([
    [100, 120, 130],
    [90, 110, 140],
    [80, 100, 120]
])

mean = image.mean(axis=0)   
std = image.std(axis=0)    

normalized_image = (image - mean) / std
print(normalized_image)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


Example 8: Centering Data in Machine Learning
Centering data is an important step in many machine learning workflows. Broadcasting helps center the data efficiently by subtracting the mean from each feature.

In [9]:
data = np.array([
    [10, 20],
    [15, 25],
    [20, 30]
])

feature_mean = data.mean(axis=0)

centered_data = data - feature_mean
print(centered_data)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]
