NumPy stands for Numerical Python and is used for handling large, multi-dimensional arrays and matrices. Unlike Python's built-in lists NumPy arrays provide efficient storage and faster processing for numerical and scientific computations. It offers functions for linear algebra and random number generation making it important for data science and machine learning.

##### 1. One Dimensional Array:
A one-dimensional array is a type of linear array.



In [8]:
import numpy as np
list_1=[1,2,3,4,5]
sample_array=np.array(list_1)
print("list in python: ",list_1)
print("numpy array in python: ",sample_array)

list in python:  [1, 2, 3, 4, 5]
numpy array in python:  [1 2 3 4 5]


In [2]:
print(type(list_1))

print(type(sample_array))

<class 'list'>
<class 'numpy.ndarray'>


##### 2. Multi-Dimensional Array:
A Multi-Dimensional Array is an array that can store data in more than one dimension such as rows and columns. In simple terms it is a array of arrays.

For example a 2D array is like a table with rows and columns where each element is accessed by two indices: one for the row and one for the column. Higher dimensions like 3D arrays involve adding additional layers. 

* Note: use [ ] operators inside numpy.array() for multi-dimensional.

In [3]:

list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

sample_array = np.array([list_1, 
                         list_2,
                         list_3])
print("Numpy multi dimensional array in python\n",
      sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


###### Parameters of a Numpy Array
1. Axis: Axis of an array describes the order of the indexing into the array.  
Axis 0 = one dimensional  
Axis 1 = Two dimensional  
Axis 2 = Three dimensional


###### 2. Shape: Number of elements along with each axis and is returned as a tuple.

In [4]:
sample_array.shape

(3, 4)

##### 3. Rank: Rank of an array is simply the number of axes or dimensions it has.

One-dimensional array has rank 1.  
Rank 1  
Two-dimensional array has rank 2.  
Rank 2  



##### 4. Data type objects (dtype): Data type objects (dtype) is an example of numpy.dtype class. It describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.

In [5]:
sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([0.2, 0.4, 2.4])

print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of array 2 :",
      sample_array_2.dtype)

Data type of the array 1 : int64
Data type of array 2 : float64


#### Different Ways of Creating Numpy Array
1. numpy.array(): Numpy array object in Numpy is called ndarray. We can create ndarray using this function.

In [6]:
arr = np.array([3,4,5,5])

print("Array :",arr)

Array : [3 4 5 5]


2. numpy.fromiter(): The fromiter() function create a new one-dimensional array from an iterable object.

In [12]:
var="venkeyreddy"
arr=np.fromiter(var,dtype='U2')
print("nnew array: ",arr)

nnew array:  ['v' 'e' 'n' 'k' 'e' 'y' 'r' 'e' 'd' 'd' 'y']


3. numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.

In [17]:
np.arange(1,20,2,dtype=np.int64)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4. numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits. 

In [26]:
np.linspace(1,10,5,dtype=np.int32)

array([ 1,  3,  5,  7, 10], dtype=int32)

5. numpy.empty(): This function create a new array of given shape and type without initializing value.

In [28]:
np.empty([4,3],dtype=np.int32,order='f')

array([[         0,          0,          0],
       [1072693248, 1074790400, 1075838976],
       [         0,          0,          0],
       [1073741824, 1075314688, 1076101120]], dtype=int32)

6. numpy.ones(): This function is used to get a new array of given shape and type filled with ones (1).

In [30]:
np.ones([5,5],dtype=np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

7. numpy.zeros(): This function is used to get a new array of given shape and type filled with zeros (0). 

In [31]:
np.zeros([5,5],dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)